version: '3.8'

services:

  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: autoflixx
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-cloud-network

  # Eureka Server
  eureka-server:
    build:
      context: ./eurekaserver
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network

  # Config Server
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - spring-cloud-network

  # Confiteria Service
  confiteria-service:
    build:
      context: ./confiteria-services
    container_name: confiteria-service
    ports:
      - "8081:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.cloud.config.uri=http://config-server:8888
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/autoflixx?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - spring.datasource.username=user
      - spring.datasource.password=userpassword
    depends_on:
      - mysql-db
      - eureka-server
      - config-server
    networks:
      - spring-cloud-network

  # Movies Service
  movies-service:
    build:
      context: ./movies-services
    container_name: movies-service
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.cloud.config.uri=http://config-server:8888
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/autoflixx?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - spring.datasource.username=user
      - spring.datasource.password=userpassword
    depends_on:
      - eureka-server
      - config-server
    networks:
      - spring-cloud-network

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
      - confiteria-service
      - movies-service
    networks:
      - spring-cloud-network

volumes:
  mysql-data:

networks:
  spring-cloud-network:
    driver: bridge
